# Generated by Django 4.1.4 on 2023-01-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_phone_info_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phone_info',
        ),
    ]
