version: "3"

services:
  
  
  app:
    build: .
    volumes:
      - .:/django-app
    ports:
      - 8000:8000
    image: app:django-app
    container_name: django-app_container 
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    container_name: postgres_db