# Generated by Django 4.1.4 on 2023-01-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.CharField(max_length=255)),
                ("total_quantity", models.CharField(max_length=255)),
                ("add_datetime", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cart_items_auth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("quantity", models.CharField(default="", max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("add_datetime", models.DateTimeField(auto_now_add=True)),
                ("update_datetime", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.items"
                    ),
                ),
            ],
        ),
    ]
