# Generated by Django 4.1.4 on 2023-01-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_rename_item_info_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('user', models.CharField(max_length=255)),
                ('quantity', models.CharField(default='', max_length=255)),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.items')),
            ],
        ),
    ]
