# Generated by Django 4.1.4 on 2023-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_cart_items_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(max_length=255)),
                ('total_quantity', models.CharField(max_length=255)),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
