# Generated by Django 4.1.4 on 2023-01-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items_auth',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
