# Generated by Django 4.1.4 on 2023-01-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_iphone_info_item_info_delete_laptop_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item_info',
            new_name='Items',
        ),
    ]
